#!/bin/sh

#########
# SSH Config for CentOS 7.4 Server Script
# Author: Paul Guest <paul.guest@acadsol.co.uk>
# Version: v0.1, 2018-03-28
# Source: https://github.com/berferd67/bitcoind
#########

########
#Harden ssh server
########

#Configure keys based authentication

cd ~/
mkdir ~/.ssh
ssh-keygen -t rsa
chmod 700 ~/.ssh
chmod 600 ~/.ssh/id_rsa
cat id_rsa.pub >> ~/.ssh/authorized_keys
chmod 700 ~/.ssh
chmod 600 ~/.ssh/authorized_keys

#
#Install Fail2Ban
#
git clone https://github.com/fail2ban/fail2ban.git
cd fail2ban
sudo python setup.py install 

#
#Get Firewall to drop reapeated failed attempts with a TCP reset
#
sudo firewall-cmd --add-port 22/tcp
sudo firewall-cmd --add-port 22/tcp --permanent
sudo firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT_direct 0 -p tcp --dport 22 -m state --state NEW -m recent --set
sudo firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT_direct 1 -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 30 --hitcount 4 -j REJECT --reject-with tcp-reset
sudo firewall-cmd --reload

#
#Comment out existing entries and append config to eof
#

cp /etc/ssh/sshd_config /etc/ssh/sshd_config.ORIG

echo "########" >> /etc/ssh/sshd_config
echo "# Installation Script Hardening Entries" >> /etc/ssh/sshd_config
echo "########" >> /etc/ssh/sshd_config
echo " " >> /etc/ssh/sshd_config

#Disable root logins
sed -i "s/PermitRootLogin/#PermitRootLogin/g" /etc/ssh/sshd_config
echo "#Disable root logins" >> /etc/ssh/sshd_config
echo "PermitRootLogin no" >> /etc/ssh/sshd_config
echo " " >> /etc/ssh/sshd_config

#Allow certain users access
sed -i "s/AllowUsers/#AllowUsers/g" /etc/ssh/sshd_config
echo "#Allow certain users access" >> /etc/ssh/sshd_config
echo "AllowUsers %USER" >> /etc/ssh/sshd_config
echo " " >> /etc/ssh/sshd_config

#Disable Protocol 1
sed -i "s/Protocol/#Protocol/g" /etc/ssh/sshd_config
echo "#Disable Protocol 1" >> /etc/ssh/sshd_config
echo "Protocol 2" >> /etc/ssh/sshd_config
echo " " >> /etc/ssh/sshd_config

#Disable password authentication forcing use of keys
sed -i "s/PasswordAuthentication/#PasswordAuthentication/g" /etc/ssh/sshd_config
echo "#Disable password authentication forcing use of keys" >> /etc/ssh/sshd_config
echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
echo " " >> /etc/ssh/sshd_config

#Display instructions to copy key to remote host
echo "########"
echo "Make sure you copy the key to a remote client BEFORE disabling password authentication"
echo "########"
echo "Use the following commands on a REMOTE client"
echo "Copy the secret key to local ssh directory"
echo "Don't f*ck this up or you'll lock yourself out"
echo "########"
echo "mkdir ~/.ssh "
echo "chmod 700 ~/.ssh"
echo "scp %user@%host:/%home/%user/.ssh/id_rsa ~/.ssh/"

#Wait for the user to respond
read -p "Hit Enter to continue once you've copied the key"

#Confirm remote access
echo "Confirm remote access before continuing"
echo "ssh %user@%host"
read -p "Hit Enter when you're sure you have key based access"

#restart ssh service
/etc/init.d/networking restart
