#!/bin/sh

#########
# Bitcoind and c-lightning on CentOS 7.4 Server Script
# Author: Paul Guest <paul.guest@acadsol.co.uk>
# Version: v0.1, 2018-03-28
# Source: https://github.com/berferd67/bitcoind
#########

########
# Check whether script is running as root
########

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

########
# Set Hostname
########

#Assign existing hostname to $HOSTNAME
HOSTNAME=$(cat /etc/hostname)

#Display existing hostname
echo "Existing hostname is $HOSTNAME"

#Ask for new domainname $DOMAIN
echo "Enter new domain name: "
read DOMAIN

#Ask for new hostname $NEWHOST
echo "Enter new hostname: "
read NEWHOST

#change hostname in /etc/hosts & /etc/hostname
sudo sed -i "s/$HOSTNAME/$NEWHOST/g" /etc/hosts
sudo sed -i "s/$HOSTNAME/$NEWHOST/g" /etc/hostname

#display new hostname
echo "Your new hostname is $NEWHOST"


########
# Update repos and install updates
########

#Install dev tools
#apt-get install -y autoconf automake build-essential git libtool libgmp-dev libsqlite3-dev python python3 net-tools libsodium-dev
yum install -y clang gmp-devel libsq3-devel net-tools libsodium-devel valgrind wget git asciidoc
sudo yum clean all

#Install Python3
sudo yum -y install https://centos7.iuscommunity.org/ius-release.rpm
sudo yum -y install python36u
sudo yum -y install python36u-pip
sudo yum -y install python36u-devel
sudo pip3.6 install python-bitcoinlib
sudo pip3.6 install --upgrade pip


#Add a user to be used for bitcoind and lightningd
echo "Enter username for new user: "
read NEWUSER
adduser $NEWUSER
echo "Enter new password for new user: "
read NEWPASSWORD
echo $NEWPASSWORD |passwd $NEWUSER --stdin

########
#Configure Uncomplicated Firewall to allow access to ssh, bitcoind and lightningd
########

firewall-cmd --add-port 22/tcp
firewall-cmd --add-port 22/tcp --permanent
firewall-cmd --add-port 8333/tcp
firewall-cmd --add-port 8333/tcp --permanent
firewall-cmd --add-port 9735/tcp
firewall-cmd --add-port 9735/tcp --permanent





########
#Install Bitcoin and Lightning
########

#Install Bitcoind
apt-get install software-properties-common
add-apt-repository ppa:bitcoin/bitcoin
apt-get update
apt-get install -y bitcoind

#Install Lightning
git clone https://github.com/ElementsProject/lightning.git
cd lightning
./configure
make

#Create crontab entries to start services at reboot
sudo -i -u $NEWUSER bash << EOF
echo "@reboot /usr/local/bin/bitcoind -daemon" >> /var/spool/cron/$NEWUSER
echo "@reboot /home/"$NEWUSER"/lightning/lightningd" >> /var/spool/cron/$NEWUSER
# ./lightningd/lightningd &
# ./cli/lightning-cli help
#EOF
#Run bitcoind and lightningd
#sudo -i -u $NEWUSER bash << EOF
# bitcoind &
# ./lightningd/lightningd &
# ./cli/lightning-cli help
#EOF
